version: '3'
services:
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    volumes:
      - rails-next-db-store:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
    ports:
      - "3306:3306"

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    volumes:
      - ./backend:/app
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "80:80"

    depends_on:
      - backend
      - frontend

volumes:
  rails-next-db-store:
